error_reporting = E_ALL
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /proc/self/fd/2
expose_php = Off
allow_url_include = Off
date.timezone = UTC
upload_tmp_dir = /var/lib/q2a/upload-temp
upload_max_filesize = 16M
post_max_size = 20M
memory_limit = 256M
session.cookie_httponly = 1
session.cookie_samesite = Lax
